# Generated by Django 5.0.3 on 2024-04-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='preview_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/category_photos'),
        ),
        migrations.AlterField(
            model_name='mainblogphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog_photos/main_photo/'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/products_photos/main_photo'),
        ),
        migrations.AlterField(
            model_name='secondaryblogphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog_photos/secondary_photos/'),
        ),
        migrations.AlterField(
            model_name='secondaryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/products_photos/secondary_photos'),
        ),
    ]
