# Generated by Django 5.0.4 on 2024-04-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='preview_photo',
            field=models.ImageField(blank=True, upload_to='category_photos'),
        ),
        migrations.AlterField(
            model_name='mainblogphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_photos/main_photo/'),
        ),
        migrations.AlterField(
            model_name='mainphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_photos/main_photo'),
        ),
        migrations.AlterField(
            model_name='secondaryblogphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_photos/secondary_photos/'),
        ),
        migrations.AlterField(
            model_name='secondaryphoto',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_photos/secondary_photos'),
        ),
    ]
