# Generated by Django 5.0.3 on 2024-04-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_title_en_alter_category_preview_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_en',
        ),
    ]
